### PR TITLE
Fixed a few things. Added the icon.

### PR DESCRIPTION
**Pull request by yurablok**
Fixed:
1. Redudant overwriting of a file that is already saved in UTF-8.
**This bug breaks the Visual Studio system that shows modified lines of code by highlighting the area to their left and the area on the scroll bar.** 
2. UTF-8 with BOM not automatically converted to UTF-8 no BOM.

A simple icon for the extension has also been added.

### CODE REVIEW

**Comment by matriox1003** [comment]
Hey , I want to know how to uninstall it

**Comment by yurablok** [comment]
> Hey , I want to know how to uninstall it

Questions on how to uninstall any extensions are general questions and not relevant to the topic.
Anyway, use the menu: Extensions -> Manage Extensions -> Installed -> %extension% -> Uninstall.

**Comment by PhilCS** [comment]
@andrei-turcan Would it be possible for you to update the store extension to 0.0.4, please? Thanks!

**Comment by PhilCS** [comment]
@yurablok Thanks, that works perfectly!

**Pull request merged**
